### ISSUE TITLE
tailscale 1.58.0 rollout paused

### ISSUE THREAD

**Issue by gclawes** [mato/tailscale-turris#2]
I noticed tailscale 1.58.0 is in this repo's `stable` track.  According to upstream tailscale, this rollout is paused due to a possible regression: https://tailscale.com/changelog

**Comment by gclawes** [comment]
It looks like v1.58.2 has been released to address this, and I see it in the repo, thanks!

**Comment by mato** [comment]
Sorry about that. FYI the process by which the packages flow into the repo is entirely automated and runs twice daily.

**Comment by gclawes** [comment]
No problem.  Thanks for building this, I finally can get away from that nagging security warning due to the ancient package in Turris's upstream OpenWRT.
